// Package suggestfixes provides functionality for the suggestfixes subsystem.
package suggestfixes

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"strings"

	"mcp-server-go-refactor/internal/engine"
	"mcp-server-go-refactor/internal/models"
	"mcp-server-go-refactor/internal/registry"
	"mcp-server-go-refactor/internal/staging"
	"mcp-server-go-refactor/internal/util"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/tidwall/buntdb"
)

// Tool implements the suggest_fixes tool.
type Tool struct {
	Engine *engine.Engine
}

// Name performs the Name operation.
func (t *Tool) Name() string {
	return "suggest_fixes"
}

// Register performs the Register operation.
func (t *Tool) Register(s util.SessionProvider) {
	util.HardenedAddTool(s, &mcp.Tool{
		Name:        t.Name(),
		Description: "[ROLE: PLANNER] [PHASE: PROPOSAL] CODE CHANGE PROPOSER: Aggregates ALL prior analysis diagnostics (complexity, dead code, coverage, context, security, modernization) and recall standards into prioritized refactoring fix recommendations. Essential for evaluating and refactoring Go idioms, resolving technical debt, and modernizing compliance. [REQUIRES: brainstorm:aporia_engine, brainstorm:brainstorm_ast_probe] [TRIGGERS: go-refactor:go_test_validation] Keywords: suggest, fixes, propose, refactor, evaluate, go, idioms, compliance, synthesize, resolve",
	}, t.Handle)
}

// Register adds the suggest_fixes tool to the registry.
func Register(eng *engine.Engine) {
	registry.Global.Register(&Tool{Engine: eng})
}

// SuggestFixesInput defines the expected arguments.
type SuggestFixesInput struct {
	models.UniversalPipelineInput
}

// Handle performs the Handle operation.
func (t *Tool) Handle(ctx context.Context, _ *mcp.CallToolRequest, input SuggestFixesInput) (*mcp.CallToolResult, any, error) {
	var goldenTruth string
	var session *engine.Session

	isOrchestrator := os.Getenv("MCP_ORCHESTRATOR_OWNED") == "true"
	recallAvailable := isOrchestrator && t.Engine != nil && t.Engine.ExternalClient != nil && t.Engine.ExternalClient.RecallEnabled()
	if isOrchestrator && !recallAvailable {
		slog.Warn("[ORCHESTRATOR] recall unavailable — degrading to standalone", "tool", t.Name())
	}

	if t.Engine != nil {
		session = t.Engine.LoadSession(ctx, input.Target)
	}

	var diagnostics []string
	if diags, ok := input.Flags["diagnostics"].([]string); ok {
		diagnostics = diags
	}

	// Read cached standards populated by previous stages
	if t.Engine != nil {
		// Load historical fix suggestions for this package to detect recurring patterns.
		if recallAvailable {
			if history := t.Engine.LoadCrossSessionFromRecall(ctx, "go-refactor", input.Target); history != "" {
				if session.Metadata == nil {
					session.Metadata = make(map[string]any)
				}
				session.Metadata["historical_fixes"] = history
			}
		}

		// Dynamic BuntDB scan: collect ALL recall_cache_* entries from every stage
		var truths []string
		if t.Engine.DB != nil {
			_ = t.Engine.DB.View(func(tx *buntdb.Tx) error {
				return tx.AscendKeys("recall_cache_*", func(key, value string) bool {
					var wrapper engine.SyncWrapper
					if err := json.Unmarshal([]byte(value), &wrapper); err == nil && wrapper.Data != "" {
						truths = append(truths, wrapper.Data)
					} else if value != "" {
						truths = append(truths, value) // Legacy string fallback
					}
					return true
				})
			})
		}

		// Load past internal diagnostics generated by previous tools directly from memory
		if diags, ok := session.Metadata["diagnostics"].([]string); ok {
			diagnostics = append(diagnostics, diags...)
		}

		// Extract keywords for BM25 query expansion
		var dynamicKeywords string
		if len(diagnostics) > 0 {
			var b strings.Builder
			for i, d := range diagnostics {
				if i >= 5 {
					break
				}
				b.WriteString(d)
				b.WriteString(" ")
			}
			dynamicKeywords = b.String()
			if len(dynamicKeywords) > 200 {
				dynamicKeywords = dynamicKeywords[:200]
			}
		}

		// Recall-based best-practice query (gated).
		var bestPractices string
		if recallAvailable {
			archQuery := "Go refactoring best practices, fix prioritization, and risk mitigation standards for " + input.Target + " " + dynamicKeywords
			memQuery := "Go 1.26 GC optimization, heap allocation reduction, sync.Pool, zero-copy byte slice standards " + dynamicKeywords
			concQuery := "Goroutine leak prevention, mutex contention standards " + dynamicKeywords

			bpArch := t.Engine.EnsureRecallCache(ctx, session, "fix_standards_arch", "search", map[string]any{"namespace": "ecosystem", "query": archQuery, "limit": 5})
			bpMem := t.Engine.EnsureRecallCache(ctx, session, "fix_standards_mem", "search", map[string]any{"namespace": "ecosystem", "query": memQuery, "limit": 5})
			bpConc := t.Engine.EnsureRecallCache(ctx, session, "fix_standards_conc", "search", map[string]any{"namespace": "ecosystem", "query": concQuery, "limit": 5})

			bestPractices = strings.TrimSpace(bpArch + "\n\n" + bpMem + "\n\n" + bpConc)
		}

		session.Metadata["recall_cache_synthesis"] = bestPractices
		if bestPractices != "" {
			truths = append(truths, bestPractices)
		}

		if len(truths) > 0 {
			goldenTruth = strings.Join(truths, "\n\n---\n\n")
		}
	}

	if goldenTruth == "" {
		goldenTruth = "[Note: Recall server was offline or matched no memories. Proceeding with raw diagnostics.]"
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Proposal for Package: %s\n\n", input.Target))
	sb.WriteString("## Diagnostics to Address\n")
	if len(diagnostics) == 0 {
		sb.WriteString("- No prior diagnostics provided.\n")
	} else {
		for _, d := range diagnostics {
			sb.WriteString(fmt.Sprintf("- %s\n", d))
		}
	}

	sb.WriteString("\n## Referenced Standards (from Recall)\n")
	sb.WriteString(goldenTruth + "\n")

	sb.WriteString("\n## Next Steps\n")
	sb.WriteString("Evaluate this proposal utilizing the Brainstorm MCP Server to refine the architectural alignment and output a concrete implementation strategy.\n")

	proposalText := sb.String()

	// Phase 1: Publish cumulative session state to recall for cross-server intelligence.
	if session != nil && session.Metadata != nil {
		// Publish fix suggestions trace to recall sessions matrix.
		if recallAvailable {
			t.Engine.PublishSessionToRecall(ctx, input.SessionID, input.Target, "fixes_suggested", "native", "suggest_fixes", "", session.Metadata)
		}
	}

	var stagingURI string
	if t.Engine != nil && t.Engine.DB != nil {
		payload := map[string]string{
			"proposal":     proposalText,
			"golden_truth": goldenTruth,
		}
		if uri, err := staging.SavePayload(t.Engine.DB, payload); err == nil {
			stagingURI = uri
		} else {
			slog.Error("[suggest_fixes] failed to stage payload", "error", err)
		}
	}

	return &mcp.CallToolResult{}, struct {
		Summary     string   `json:"summary"`
		StagingURI  string   `json:"staging_uri,omitempty"`
		Pkg         string   `json:"pkg"`
		Diagnostics []string `json:"diagnostics"`
	}{
		Summary:     fmt.Sprintf("Synthesized proposal for %s relying on %d diagnostics.", input.Target, len(diagnostics)),
		StagingURI:  stagingURI,
		Pkg:         input.Target,
		Diagnostics: diagnostics,
	}, nil
}
