// Package handler provides functionality for the handler subsystem.
package handler

import (
	"fmt"
	"mcp-server-magicdev/internal/db"
	"strings"
)

// GenerateMermaidDiagram translates a Blueprint into an Application Architecture Graph.
func GenerateMermaidDiagram(session *db.SessionState, bp *db.Blueprint) string {
	if bp == nil {
		return ""
	}

	var sb strings.Builder
	sb.WriteString("\n```mermaid\ngraph TD\n")
	sb.WriteString("    %% Application Architecture Graph generated by MagicDev\n\n")

	hasModules := session != nil && session.DesignProposal != nil && len(session.DesignProposal.ProposedModules) > 0

	if hasModules {
		sb.WriteString("    subgraph Core Architecture\n")
		// Define modules
		for i, mod := range session.DesignProposal.ProposedModules {
			modID := fmt.Sprintf("mod%d", i)
			safeName := strings.ReplaceAll(mod.Name, "\"", "'")
			sb.WriteString(fmt.Sprintf("        %s[\"%s\"]\n", modID, safeName))
		}
		// Define edges (dependencies)
		for i, mod := range session.DesignProposal.ProposedModules {
			modID := fmt.Sprintf("mod%d", i)
			for _, depName := range mod.Dependencies {
				// Find target module index
				for j, target := range session.DesignProposal.ProposedModules {
					if target.Name == depName {
						targetID := fmt.Sprintf("mod%d", j)
						sb.WriteString(fmt.Sprintf("        %s --> %s\n", modID, targetID))
						break
					}
				}
			}
		}
		sb.WriteString("    end\n\n")
	} else {
		// Fallback for missing module data
		sb.WriteString("    App[Application Core]\n\n")
	}

	if len(bp.MCPTools) > 0 || len(bp.MCPResources) > 0 || len(bp.MCPPrompts) > 0 {
		sb.WriteString("    subgraph MCP Interfaces\n")
		// Try to attach interfaces to the Core or App
		attachTarget := "App"
		if hasModules {
			attachTarget = "mod0" // Attach to the first module
		}

		for i, tool := range bp.MCPTools {
			nodeID := fmt.Sprintf("tool%d", i)
			safeName := strings.ReplaceAll(tool.Name, "\"", "'")
			sb.WriteString(fmt.Sprintf("        %s([\"Tool: %s\"])\n", nodeID, safeName))
			sb.WriteString(fmt.Sprintf("        %s -.-> %s\n", attachTarget, nodeID))
		}
		for i, res := range bp.MCPResources {
			nodeID := fmt.Sprintf("res%d", i)
			safeName := strings.ReplaceAll(res.Name, "\"", "'")
			sb.WriteString(fmt.Sprintf("        %s([\"Resource: %s\"])\n", nodeID, safeName))
			sb.WriteString(fmt.Sprintf("        %s -.-> %s\n", attachTarget, nodeID))
		}
		for i, prompt := range bp.MCPPrompts {
			nodeID := fmt.Sprintf("prompt%d", i)
			safeName := strings.ReplaceAll(prompt.Name, "\"", "'")
			sb.WriteString(fmt.Sprintf("        %s([\"Prompt: %s\"])\n", nodeID, safeName))
			sb.WriteString(fmt.Sprintf("        %s -.-> %s\n", attachTarget, nodeID))
		}
		sb.WriteString("    end\n\n")
	} else if len(bp.APIContracts) > 0 {
		sb.WriteString("    subgraph API Interfaces\n")
		attachTarget := "App"
		if hasModules {
			attachTarget = "mod0"
		}
		for i, api := range bp.APIContracts {
			nodeID := fmt.Sprintf("api%d", i)
			sb.WriteString(fmt.Sprintf("        %s([\"%s %s\"])\n", nodeID, api.Method, api.Path))
			sb.WriteString(fmt.Sprintf("        %s -.-> %s\n", attachTarget, nodeID))
		}
		sb.WriteString("    end\n\n")
	}

	if len(bp.DataModel) > 0 {
		sb.WriteString("    subgraph Storage\n")
		for i, entity := range bp.DataModel {
			entID := fmt.Sprintf("ent%d", i)
			safeName := strings.ReplaceAll(entity.Name, "\"", "'")
			sb.WriteString(fmt.Sprintf("        %s[(\"%s\")]\n", entID, safeName))
		}
		sb.WriteString("    end\n")
	}

	sb.WriteString("```\n\n")
	return sb.String()
}
