// Package db provides BuntDB-backed session persistence for the MagicDev
// pipeline state machine. Each session tracks the lifecycle of a requirements
// engineering workflow from idea evaluation through document generation.
package db

// Dependency represents a single package in the dependency manifest
// produced by the blueprint_implementation tool.
type Dependency struct {
	Name      string `json:"name"`
	Version   string `json:"version"`
	Ecosystem string `json:"ecosystem"` // "nuget" or "npm"
}

// Blueprint holds the technical implementation strategy generated by the
// MCP sampling protocol. It maps finalized requirements to concrete patterns,
// packages, complexity estimates, and contradiction resolutions.
type Blueprint struct {
	ImplementationStrategy map[string]string `json:"implementation_strategy"` // requirement → pattern mapping
	DependencyManifest     []Dependency      `json:"dependency_manifest"`
	ComplexityScores       map[string]int    `json:"complexity_scores"`    // feature → 1-13 story points
	AporiaTraceability     map[string]string `json:"aporia_traceability"` // contradiction → resolution pattern
}

// SessionState holds the pipeline state for a given session. Each field
// corresponds to data produced or consumed by one or more tools in the
// idea-to-asset pipeline.
type SessionState struct {
	SessionID         string            `json:"session_id"`
	TechStack         string            `json:"tech_stack"`
	Standards         []string          `json:"standards"`                       // dynamically ingested rules
	StepStatus        map[string]string `json:"step_status"`                    // tracking progress
	CurrentStep       string            `json:"current_step,omitzero"`
	FinalSpec         string            `json:"final_spec,omitzero"`            // Golden Copy from finalize_requirements
	AporiaResolutions []string          `json:"aporia_resolutions,omitzero"`    // contradictions found during clarify
	Blueprint         *Blueprint        `json:"blueprint,omitzero"`
}

// NewSessionState initializes a fresh session with zeroed collections
// to prevent nil-map panics during downstream tool execution.
func NewSessionState(sessionID string) *SessionState {
	return &SessionState{
		SessionID:         sessionID,
		Standards:         make([]string, 0),
		StepStatus:        make(map[string]string),
		AporiaResolutions: make([]string, 0),
	}
}
